### ISSUE TITLE
User balance of testnet not shown

### ISSUE THREAD

**Issue by hussu010** [Keysign-Wallet/Keysign-mobile-testing#1]
Proof:

https://user-images.githubusercontent.com/55182298/133367341-da6c10da-9e32-4d5c-9fc3-6e723bdba1fe.mp4

**Comment by mrbusysky** [comment]
This is an emulator, so not much we can do about this until we find a solution for it.

This emulator seems to be blocking the connection.

Or you aren't using a wallet with a balance it it.

**Comment by mrbusysky** [comment]
This bug is solved. Emulators do not like non HTTP connections by default.
